from pathlib import Path
from html import escape
import json
import os
ROOT=Path('dist')
OFF='https://www.ieor.iitb.ac.in'
NAV=[('Academics','/academics/'),('Admissions','/admissions/'),('Research','/research/'),('People','/people/'),('Opportunities','/opportunities/'),('About','/about/')]
PROGRAMS=[
 ('B.Tech','Industrial Engineering and Operations Research','/academics/btech/','An undergraduate path through engineering foundations, IEOR methods, laboratories, electives and project work.','/acad/btech','/admissions/btech'),
 ('M.Tech','Industrial Engineering and Operations Research','/academics/mtech/','Graduate study combining methods, applications, electives and a research thesis.','/acad/mtech','/admissions/mtech'),
 ('M.Sc','Operations Research','/academics/msc/','A four-semester path with foundational and advanced coursework and project work.','/acad/msc','/admissions/msc'),
 ('M.Sc.–Ph.D.','Operations Research','/academics/msc-phd/','An integrated route from postgraduate coursework toward doctoral research.','/acad/msc_phd','/admissions/msc'),
 ('Ph.D.','Industrial Engineering and Operations Research','/academics/phd/','Original research with faculty guidance, culminating in a dissertation.','/acad/phd','/admissions/phd'),
]
TOPICS=[('Optimization','Models, theory and algorithms','/node/3000'),('Stochastic systems','Models and control under uncertainty','/node/3001'),('Simulation','Analysis of complex systems','/node/3099'),('AI & learning','Data-driven methods and decisions','/node/3003'),('Logistics & transportation','Networks, mobility and movement','/node/3005'),('Supply chains','Inventory and planning','/node/3009')]
NEWS=[('24 Sep 2026','Prof. Urban Larsson delivers talk on combinatorial game theory','/node/4074'),('September 2026','IEOR inaugurates Golden Jubilee celebrations','/node/4069'),('22 Aug 2026','64th Convocation and Departmental Degree Award Function','/node/4063')]
EVENTS=[('30 Sep 2026 · 5:30 pm','IEOR Talks by Prof. Parthanil Roy','LA 002, Lecture Hall Complex','/node/4070'),('23 Oct 2026 · 12:00 pm','ODTL 2026 Workshop','PC Saxena Auditorium, IIT Bombay','/node/4071')]
def ext(path):return OFF+path

def linklist(items):return '<ul class="link-list">'+''.join(f'<li><a href="{u}">{escape(t)}</a></li>' for t,u in items)+'</ul>'
def card(title,desc,url,label='Explore',eyebrow=''):
 return f'<article class="card"><div class="small">{escape(eyebrow)}</div><h3><a class="title-link" href="{url}">{escape(title)}</a></h3><p>{escape(desc)}</p><a class="action" href="{url}">{escape(label)}</a></article>'
def header(active):
 nav=''.join(f'<a href="{u}"'+(' aria-current="page"' if active==u else '')+f'>{t}</a>' for t,u in NAV)
 return f'''<a class="skip" href="#main">Skip to content</a><div class="utility"><div class="wrap"><span>Indian Institute of Technology Bombay</span><a href="{OFF}" target="_blank" rel="noopener">Current department website</a></div></div><header class="site-header"><div class="wrap header-inner"><a class="brand" href="/" aria-label="IEOR IIT Bombay home"><img class="brand-logo" src="/assets/golden-jubilee-logo.png" alt="" width="82" height="82"><span><span class="brand-name">IEOR</span><span class="brand-sub">Industrial Engineering &amp;<br>Operations Research · IIT Bombay</span></span></a><button class="menu-toggle" aria-controls="site-nav" aria-expanded="false">Menu</button><nav class="nav" id="site-nav" aria-label="Main navigation">{nav}</nav><a class="header-cta" href="/contact/">Contact IEOR</a></div></header>'''
def footer():
 return f'''<footer class="footer"><div class="wrap"><div class="footer-grid"><div><h3>IEOR · IIT Bombay</h3><p>Department of Industrial Engineering and Operations Research<br>Powai, Mumbai 400076, India</p><p>This public redesign preview summarizes departmental information. For official notices, deadlines and regulations, consult the <a href="{OFF}" target="_blank" rel="noopener">current IEOR website</a>.</p></div><div><h3>Explore</h3><ul><li><a href="/academics/">Academics</a></li><li><a href="/admissions/">Admissions</a></li><li><a href="/research/">Research</a></li><li><a href="/people/">People</a></li></ul></div><div><h3>Engage</h3><ul><li><a href="/opportunities/">Opportunities</a></li><li><a href="/news-events/">News &amp; events</a></li><li><a href="/contact/">Contact</a></li><li><a href="{ext('/node/3911')}">Alumni</a></li></ul></div><div><h3>Current resources</h3><ul><li><a href="{ext('/acad/courses')}">Course catalog</a></li><li><a href="{ext('/acad/timetable')}">Timetable</a></li><li><a href="{ext('/resource/forms')}">Forms</a></li><li><a href="{ext('/all_announcements')}">Announcements</a></li></ul></div></div><div class="footer-bottom"><span>Academic website concept · 2026</span><span><a href="https://www.iitb.ac.in/">IIT Bombay</a> · <a href="{OFF}">Current IEOR website</a></span></div></div></footer>'''
def page(title,description,body,active='',hero=None):
 head=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0a314e"><meta name="description" content="{escape(description,quote=True)}"><title>{escape(title)} · IEOR IIT Bombay</title><link rel="icon" type="image/svg+xml" href="/assets/favicon.svg"><link rel="stylesheet" href="/assets/site.css"></head><body>'''
 lead=hero if hero is not None else f'<div class="page-hero"><div class="wrap"><div class="breadcrumbs"><a href="/">Home</a> / {escape(title)}</div><div class="eyebrow">IEOR · IIT Bombay</div><h1>{escape(title)}</h1><p>{escape(description)}</p></div></div>'
 return head+header(active)+f'<main id="main">{lead}{body}</main>'+footer()+'''<script>const b=document.querySelector('.menu-toggle'),n=document.querySelector('#site-nav');b.addEventListener('click',()=>{const o=b.getAttribute('aria-expanded')==='true';b.setAttribute('aria-expanded',String(!o));n.classList.toggle('open',!o)});</script></body></html>'''
def write(path,html):
 target=ROOT/path/'index.html' if path else ROOT/'index.html';target.parent.mkdir(parents=True,exist_ok=True);target.write_text(html,encoding='utf8')

# Home
program_cards=''.join(card(p[0],p[3],p[2],eyebrow=p[1]) for p in (PROGRAMS[0],PROGRAMS[1],PROGRAMS[2],PROGRAMS[4]))
topic_links=''.join(f'<a href="{ext(u)}"><span>{escape(a)}<br><small style="font-weight:500;color:var(--muted)">{escape(b)}</small></span></a>' for a,b,u in TOPICS)
news_cards=''.join(f'<article class="update-card"><time>{d}</time><h3><a href="{ext(u)}">{escape(t)}</a></h3></article>' for d,t,u in NEWS[:2])
hero='''<div class="hero"><div class="wrap hero-inner"><div class="hero-copy"><div class="eyebrow">Department of Industrial Engineering &amp; Operations Research</div><h1>Better decisions for complex systems.</h1><p class="lead">At IIT Bombay, IEOR brings mathematical models, computation and a systems perspective to challenges in industry and society.</p><div class="hero-actions"><a class="button button-light" href="/academics/">Explore academics</a><a class="button button-outline" href="/research/">Explore research</a></div></div><div class="hero-media"><img src="/assets/building.jpg" alt="The blue IEOR department building at IIT Bombay"><span class="caption">IEOR Building, IIT Bombay</span></div></div></div>'''
body=f'''<div class="intro-strip"><div class="wrap"><p>Operations research, industrial systems and data-driven decisions connect rigorous methods with real-world applications.</p></div></div><section class="blue-section"><div class="wrap split"><div><div class="eyebrow">Explore ideas</div><h2>Research across theory and application.</h2><p>Faculty and students work on optimization, stochastic systems, simulation, learning, logistics and more. Start with a topic, then follow the people and projects behind it.</p><a class="button button-blue" href="/research/">Research at IEOR</a></div><div class="image-frame"><img src="/assets/research.jpeg" alt="Researchers and participants at an IEOR workshop" loading="lazy"></div></div></section><section><div class="wrap"><div class="section-head"><div><div class="eyebrow">Research areas</div><h2>Questions we work on</h2></div><a class="text-link" href="{ext('/research/research-topics')}">All topics</a></div><div class="topic-list">{topic_links}</div></div></section><section><div class="wrap"><div class="section-head"><div><div class="eyebrow">Learn here</div><h2>Study IEOR</h2></div><a class="text-link" href="/academics/">All academic programs</a></div><div class="grid grid-4">{program_cards}</div></div></section><section class="dark-section"><div class="wrap jubilee-feature"><div class="jubilee-feature-copy"><div class="eyebrow">50 years of IEOR</div><h2>A community built over generations.</h2><p>IEOR marked its Golden Jubilee in 2026. Explore the department's journey and the people shaping its next chapter.</p><a class="button button-light" href="/about/">Our story</a></div><div class="jubilee-logo-panel"><img src="/assets/golden-jubilee-logo.png" alt="IEOR IIT Bombay Golden Jubilee logo, 1976 to 2026" width="320" height="320" loading="lazy"></div></div></section><section><div class="wrap"><div class="section-head"><div><div class="eyebrow">Current at IEOR</div><h2>News &amp; events</h2></div><a class="text-link" href="/news-events/">More updates</a></div><div class="updates">{news_cards}</div></div></section>'''
write('',page('Home','Industrial Engineering and Operations Research at IIT Bombay.',body,hero=hero))

# Academics
degree_names={'B.Tech':'Bachelor of Technology','M.Tech':'Master of Technology','M.Sc':'Master of Science','M.Sc.–Ph.D.':'Master of Science–Doctor of Philosophy','Ph.D.':'Doctor of Philosophy'}
pc=''.join(f'<a class="program-card" href="{p[2]}"><h3>{degree_names[p[0]]}</h3><div class="program-field">{p[1]}</div><p>{p[3]}</p></a>' for p in PROGRAMS)
body=f'''<div class="page-body"><section><div class="wrap"><div class="section-head"><div><h2>Programs offered</h2></div><p>From undergraduate study to independent research.</p></div><div class="program-list">{pc}</div></div></section><section><div class="wrap mini-grid"><div><h2>Beyond degree programs</h2><p>Explore the undergraduate minor, interdisciplinary dual degree options and continuing education offered through the department.</p>{linklist([('Undergraduate minor',ext('/acad/minor')),('Inter-Disciplinary Dual Degree Programme',ext('/acad/IDDDP')),('Continuing education',ext('/acad/cep'))])}</div><div><h2>For current students</h2><p>Current course information and timetables live on the department's maintained academic pages.</p>{linklist([('IEOR courses',ext('/acad/courses')),('Autumn 2026 timetable',ext('/acad/timetable')),('Downloadable forms',ext('/resource/forms')),('Faculty advisors',ext('/people/facultyadvisors'))])}</div></div></section></div>'''
write('academics',page('Academics','Undergraduate, master’s and doctoral pathways in industrial engineering and operations research.',body,'/academics/'))

# Program details
program_sections={
'btech':('An engineering foundation with room to explore','The published B.Tech curriculum combines compulsory IEOR courses, laboratories, departmental electives, open electives and project options. Students encounter optimization, industrial systems, computation, data analytics and uncertainty.','B.Tech admission follows the IIT Bombay undergraduate process. Current rules and requirements are maintained by the institute and department.'),
'mtech':('Methods, applications and a research thesis','The M.Tech curriculum blends mathematical and computational methods with electives and a substantial thesis. The department publishes a full-time four-semester and part-time six-semester structure.','Consult the current admissions page for categories, requirements and the application process.'),
'msc':('Foundations and project work','The published M.Sc curriculum spans four semesters of foundational and advanced study in operations research with project components.','Consult current admissions guidance for test papers and eligibility; published descriptions are being reconciled, so this preview does not restate them.'),
'msc-phd':('From coursework to doctoral research','The integrated M.Sc.–Ph.D. pathway connects postgraduate study in operations research with doctoral research, subject to the program’s current requirements.','Review the department’s current program and admissions information for the exact pathway and eligibility.'),
'phd':('Original research at IEOR','Doctoral students pursue coursework and original work with faculty, culminating in a dissertation. Research spans theoretical and applied areas.','The latest departmental call and institute admissions pages govern deadlines, categories and selection.'),
}
for p in PROGRAMS:
 key=p[2].strip('/').split('/')[-1]; section=program_sections[key];title=p[0]+' in '+p[1]
 body=f'''<div class="page-body"><section><div class="wrap mini-grid"><div><div class="eyebrow">The program</div><h2>{section[0]}</h2><p>{section[1]}</p><div class="anchor-nav"><a style="color:var(--blue);border-color:var(--line)" href="/academics/">All programs</a><a style="color:var(--blue);border-color:var(--line)" href="/research/">Research areas</a></div></div><div class="info-band"><h3>Program at a glance</h3><p>{p[3]}</p><p><strong>For exact course and degree rules:</strong> use the department's maintained curriculum.</p><a class="button button-blue" href="{ext(p[4])}">View current curriculum</a></div></div></section><section><div class="wrap mini-grid"><div><div class="eyebrow">Admissions</div><h2>How to apply</h2><p>{section[2]}</p><a class="button button-blue" href="{ext(p[5])}">Current admissions information</a></div><div><h2>Keep exploring</h2>{linklist([('Browse IEOR courses',ext('/acad/courses')),('Meet the faculty','/people/'),('Contact the department','/contact/')])}</div></div></section></div>'''
 write(p[2].strip('/'),page(title,p[3],body,'/academics/'))

# Admissions
admissions=''.join(card(p[0]+' admissions','Program overview and the department’s current application guidance.',p[2],label='Program and application route',eyebrow=p[1]) for p in (PROGRAMS[0],PROGRAMS[1],PROGRAMS[2],PROGRAMS[4]))
body=f'''<div class="page-body"><section><div class="wrap"><div class="info-band"><strong>Use current official notices.</strong><p>Eligibility, test papers, dates, fees and forms can change by cycle. The linked department and IIT Bombay admissions pages are the authority for applications.</p></div><div class="section-head" style="margin-top:55px"><div><div class="eyebrow">Choose a pathway</div><h2>Admissions by program</h2></div></div><div class="grid grid-4">{admissions}</div></div></section><section><div class="wrap mini-grid"><div><h2>Program questions?</h2><p>Explore the curriculum and research areas before applying. For a department-specific question, reach the IEOR office.</p><a class="button button-blue" href="/contact/">Contact IEOR</a></div><div><h2>Official resources</h2>{linklist([('IEOR admissions overview',ext('/admissions')),('M.Tech admissions FAQ',ext('/faq/mtech-admissions')),('IIT Bombay academic programs','https://www.iitb.ac.in/academics')])}</div></div></section></div>'''
write('admissions',page('Admissions','Choose a degree pathway and find the current official application information.',body,'/admissions/'))

# Research
research_cards=''.join(card(a,b,ext(u),label='Explore topic',eyebrow='Research area') for a,b,u in TOPICS)
body=f'''<div class="page-body"><section><div class="wrap"><div class="section-head"><div><div class="eyebrow">Methods & applications</div><h2>Explore research areas</h2></div><p>IEOR research spans mathematical methods and applications across industries and services.</p></div><div class="grid grid-3">{research_cards}</div></div></section><section class="blue-section"><div class="wrap split"><div class="image-frame"><img src="/assets/research.jpeg" alt="Participants at an IEOR research workshop" loading="lazy"></div><div><div class="eyebrow">Work and people</div><h2>Follow the research.</h2><p>Research topics connect to faculty interests, publications, student projects and computational resources. Some thesis files are available only on the IIT Bombay network.</p>{linklist([('Faculty and research interests',ext('/people/faculty')),('Publications',ext('/research/pub')),('Student projects',ext('/research/student_projects')),('Computational resources',ext('/research/comp'))])}</div></div></section><section><div class="wrap mini-grid"><div><h2>Collaborate with IEOR</h2><p>IEOR works with industry and other organizations through research, consulting, student projects and continuing education.</p><a class="button button-blue" href="/opportunities/">Explore opportunities</a></div><div><h2>Centers and labs</h2>{linklist([('FedEx ALFA',ext('/fedexalfa/')),('TCAAI at IIT Bombay','https://www.tcaai.iitb.ac.in/')])}</div></div></section></div>'''
write('research',page('Research','Methods and applications in optimization, uncertainty, simulation, learning and systems.',body,'/research/'))

# People
body=f'''<div class="page-body"><section><div class="wrap mini-grid"><div><div class="eyebrow">The community</div><h2>Find the people behind the work.</h2><p>IEOR brings together faculty, postdoctoral researchers, students and staff. Browse the maintained directories for current profiles and research interests.</p><a class="button button-blue" href="{ext('/people/faculty')}">Faculty directory</a></div><div class="image-frame"><img src="/assets/community.jpg" alt="IEOR students and faculty gathered at the 2026 convocation" loading="lazy"></div></div></section><section><div class="wrap"><div class="section-head"><div><div class="eyebrow">Directories</div><h2>Explore by role</h2></div></div><div class="grid grid-3">{card('Faculty','Research interests, profiles and contact information.',ext('/people/faculty'),eyebrow='Research & teaching')}{card('Students','Current student directory and representatives.',ext('/students'),eyebrow='Community')}{card('Staff & postdocs','Office staff and postdoctoral fellows.',ext('/people/office'),eyebrow='Support & research')}</div></div></section><section><div class="wrap mini-grid"><div><h2>Alumni</h2><p>Graduates connect the department across research, industry and public service. Explore the existing alumni network and ways to contribute.</p><a class="button button-blue" href="{ext('/node/3911')}">Alumni engagement</a></div><div><h2>Additional directories</h2>{linklist([('Postdoctoral fellows',ext('/people/postdocs')),('Student representatives',ext('/people/student_reps_26')),('Faculty advisors',ext('/people/facultyadvisors')),('Institute award winners',ext('/people/awards'))])}</div></div></section></div>'''
write('people',page('People','Meet the faculty, researchers, students and staff of IEOR.',body,'/people/'))

# Opportunities
body=f'''<div class="page-body"><section><div class="wrap"><div class="section-head"><div><div class="eyebrow">Work together</div><h2>Paths to engage</h2></div></div><div class="grid grid-3">{card('Industry collaboration','Connect with IEOR through research, student projects and continuing education.',ext('/opportunities/corporate'),eyebrow='Organizations')}{card('Recruit IEOR talent','See placement information and the institute placement office route.',ext('/opportunities/placements'),eyebrow='Employers')}{card('Faculty positions','Explore current faculty recruitment information and focus areas.',ext('/opportunities/fac_openings'),eyebrow='Candidates')}</div></div></section><section><div class="wrap mini-grid"><div><h2>Project positions</h2><p>Short-term project openings change over time. Check the current positions page for availability.</p><a class="button button-blue" href="{ext('/node/4025')}">Current positions</a></div><div><h2>Alumni engagement</h2><p>Mentorship, lectures, student opportunities and collaboration all help strengthen the IEOR community.</p><a class="button button-blue" href="{ext('/node/3911')}">Ways to participate</a></div></div></section></div>'''
write('opportunities',page('Opportunities','Work with IEOR through research, recruiting, teaching and community engagement.',body,'/opportunities/'))

# About
body=f'''<div class="page-body"><section><div class="wrap split"><div><div class="eyebrow">The department</div><h2>Models meet the world.</h2><p>IEOR combines theory, modelling and application with a systems view of engineering and operations. Its programs, research, sponsored projects, consulting and continuing education connect methods with decisions in transportation, manufacturing, services and more.</p><a class="button button-blue" href="/research/">Explore research</a></div><div class="image-frame"><img src="/assets/building.jpg" alt="IEOR department building at IIT Bombay" loading="lazy"></div></div></section><section><div class="wrap mini-grid"><div><div class="eyebrow">1976–2026</div><h2>Our journey</h2><p>Established as an interdisciplinary program in 1976, IEOR marked fifty years in 2026. The department's history includes Professor P. G. Awate's reminiscences and a decade-wise account of its development.</p><a class="button button-blue" href="{ext('/our-jounrey')}">Read the full history</a></div><div><h2>Golden Jubilee</h2><p>The Golden Jubilee celebrations were inaugurated in September 2026, bringing the community together for a year of events and reflection.</p>{linklist([('Golden Jubilee inauguration',ext('/node/4069')),('News and events','/news-events/')])}</div></div></section><section><div class="wrap mini-grid"><div><h2>Visit and contact</h2><p>Room 105, First Floor, IEOR Building<br>IIT Bombay, Powai, Mumbai 400076, India</p><a class="button button-blue" href="/contact/">Contact the department</a></div><div><h2>Stay connected</h2>{linklist([('News archive',ext('/all_news')),('Announcements',ext('/all_announcements')),('Alumni engagement',ext('/node/3911'))])}</div></div></section></div>'''
write('about',page('About IEOR','Industrial Engineering and Operations Research at IIT Bombay: our work, community and history.',body,'/about/'))

# News events
event_html=''.join(f'<article class="update-card"><time>{d}</time><h3><a href="{ext(u)}">{escape(t)}</a></h3><p>{escape(place)}</p></article>' for d,t,place,u in EVENTS)
news_html=''.join(f'<article class="update-card"><time>{d}</time><h3><a href="{ext(u)}">{escape(t)}</a></h3></article>' for d,t,u in NEWS)
body=f'''<div class="page-body"><section><div class="wrap"><div class="section-head"><div><div class="eyebrow">On the calendar</div><h2>Upcoming events</h2></div><a class="text-link" href="{ext('/node/3014')}">Department calendar</a></div><div class="updates">{event_html}</div></div></section><section><div class="wrap"><div class="section-head"><div><div class="eyebrow">From the department</div><h2>Recent news</h2></div><a class="text-link" href="{ext('/all_news')}">Full news archive</a></div><div class="updates">{news_html}</div></div></section><section><div class="wrap info-band"><h3>Dates and locations may change</h3><p>Event details and current announcements are maintained on the department's official website.</p><a href="{ext('/all_announcements')}">View all announcements</a></div></section></div>'''
write('news-events',page('News & events','Talks, workshops, research stories and community updates from IEOR.',body))

# Contact
body=f'''<div class="page-body"><section><div class="wrap mini-grid"><div><div class="eyebrow">Visit us</div><h2>IEOR Building</h2><p>Department of Industrial Engineering and Operations Research<br>Room 105, First Floor, IEOR Building<br>Indian Institute of Technology Bombay<br>Powai, Mumbai 400076, India</p><p><a href="mailto:office.ieor@iitb.ac.in">office.ieor@iitb.ac.in</a><br><a href="tel:+912225767651">+91 22 2576 7651</a> / <a href="tel:+912225767652">+91 22 2576 7652</a></p><a class="button button-blue" href="{ext('/misc/contact')}">Current contact page</a></div><div class="image-frame"><img src="/assets/building.jpg" alt="Exterior of the IEOR department building" loading="lazy"></div></div></section><section><div class="wrap mini-grid"><div><h2>Find the right information</h2>{linklist([('Admissions information','/admissions/'),('Faculty and staff directory','/people/'),('Research collaboration','/opportunities/')])}</div><div><h2>Campus</h2><p>IEOR is located on the IIT Bombay campus in Powai, Mumbai.</p>{linklist([('IIT Bombay','https://www.iitb.ac.in/'),('Department website',OFF)])}</div></div></section></div>'''
write('contact',page('Contact IEOR','Reach the Department of Industrial Engineering and Operations Research at IIT Bombay.',body))

# Separate review shells leave public pages free of review controls.
shell = Path('review-shell.html').read_text(encoding='utf8')
for mode in ('a', 'b'):
 write('review/' + mode, shell.replace('__MODE__', mode))
config_path = ROOT / 'assets/review-config.js'
if 'IEOR_REVIEW_API_URL' in os.environ or not config_path.exists():
 api_base = os.environ.get('IEOR_REVIEW_API_URL', '').rstrip('/')
 config_path.write_text('window.IEOR_REVIEW_API_BASE = ' + json.dumps(api_base) + ';\n', encoding='utf8')
print('generated',len(list(ROOT.rglob('index.html'))),'pages')
